language: ruby
rvm:
 - 2.4.1

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - psql -c 'ALTER SEQUENCE course_types_id_seq RESTART WITH 4;' 

test:
  adapter: postgresql
  database: travis_ci_test